/****   Query de  monitoramento de processos
Autor : Marcio Penna                        ****/

SELECT WAIT_RESOURCE
	,B.LAST_WAIT_TYPE
	,B.WAIT_TYPE
	,GETDATE() AS EVENTDATE
	,DB_NAME(A.DBID) AS DB
	,A.HOSTNAME
	,SPID
	,A.BLOCKED
	,A.LOGINAME
	,DATEDIFF(MI, A.LOGIN_TIME, GETDATE()) AS DURATION_M
	,SUM(B.PERCENT_COMPLETE) AS [PERCENT_COMPLETE]
	,CAST([CPU] * 1.0 / SUM(ISNULL([CPU], 1)) OVER () * 100.0 AS DECIMAL(5, 2)) AS [CPUPERCENT]
	,ESTIMATED_COMPLETION_TIME / 1000 / 60 'ESTIMATED_CONCLUSION_MIN'
	,CASE 
		WHEN A.OPEN_TRAN = 1
			AND A.STATUS = 'SLEEPING'
			THEN 'DBA: TRANSAÇÃO ABERTA (BEGIN TRAN) MAS EM SLEEPING!'
		ELSE CONVERT(VARCHAR(MAX), SUBSTRING(TEXT, COALESCE(NULLIF(STMT_START / 2, 0), 1), CASE CASE 
							WHEN STMT_END = - 1
								THEN - 1
							ELSE STMT_END / 2
							END
						WHEN - 1
							THEN DATALENGTH(TEXT)
						ELSE (
								CASE 
									WHEN STMT_END = - 1
										THEN - 1
									ELSE STMT_END / 2
									END - STMT_START / 2
								)
						END))
		END AS CMD
	,CAST([GRANTED_MEMORY_KB] * 1.0 / SUM([GRANTED_MEMORY_KB]) OVER () * 100.0 AS DECIMAL(5, 2)) AS [MEMORYPERCENT]
	,OBJECT_NAME(G.OBJECTID, G.DBID) AS OBJECTNAME
	,A.PROGRAM_NAME
	,ISNULL(CASE 
			WHEN A.PROGRAM_NAME LIKE 'SSIS%'
				THEN 'JOB-PACKAGE'
			ELSE F.NAME
			END, 'NÃO JOB') AS JOB_NAME
	,C.CLIENT_NET_ADDRESS AS IP
	,A.CMD AS TYPECMD
	,A.LOGIN_TIME
	,WAIT_RESOURCE
	,GETDATE() AS EVENTDATE
	,SUM(CPU) AS CPU
	,ISNULL(SUM(E.REQUESTED_MEMORY_KB), 1) AS REQUESTED_MEMORY_KB
	,SUM(LOGICAL_READS) AS LOGICAL_READS
	,SUM(READS) AS READS
	,SUM(WRITES) AS WRITES
	,A.STATUS
FROM SYS.SYSPROCESSES A
LEFT JOIN SYS.DM_EXEC_REQUESTS B ON A.SPID = B.SESSION_ID
INNER JOIN SYS.DM_EXEC_CONNECTIONS C ON A.SPID = C.SESSION_ID
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(A.SQL_HANDLE) G
LEFT JOIN SYS.DM_EXEC_QUERY_MEMORY_GRANTS E ON A.SPID = E.SESSION_ID
LEFT JOIN MSDB.DBO.SYSJOBS F ON F.JOB_ID = CASE 
		WHEN A.PROGRAM_NAME LIKE 'SQLAGENT - TSQL%'
			THEN SUBSTRING(PROGRAM_NAME, 38, 2) + SUBSTRING(PROGRAM_NAME, 36, 2) + SUBSTRING(PROGRAM_NAME, 34, 2) + SUBSTRING(PROGRAM_NAME, 32, 2) + '-' + SUBSTRING(PROGRAM_NAME, 42, 2) + SUBSTRING(PROGRAM_NAME, 40, 2) + '-' + SUBSTRING(PROGRAM_NAME, 46, 2) + SUBSTRING(PROGRAM_NAME, 44, 2) + '-' + SUBSTRING(PROGRAM_NAME, 48, 4) + '-' + SUBSTRING(PROGRAM_NAME, 52, 12)
		END
WHERE CASE 
		WHEN A.OPEN_TRAN = 1
			AND A.STATUS = 'SLEEPING'
			THEN 'OPEN_TRAN'
		ELSE A.STATUS
		END <> 'SLEEPING'
	AND A.STATUS <> 'SLEEPING'
	AND A.SPID <> @@SPID
GROUP BY B.LAST_WAIT_TYPE
	,B.WAIT_TYPE
	,CASE 
		WHEN A.OPEN_TRAN = 1
			AND A.STATUS = 'SLEEPING'
			THEN 'DBA: TRANSAÇÃO ABERTA (BEGIN TRAN) MAS EM SLEEPING!'
		ELSE CONVERT(VARCHAR(MAX), SUBSTRING(TEXT, COALESCE(NULLIF(STMT_START / 2, 0), 1), CASE CASE 
							WHEN STMT_END = - 1
								THEN - 1
							ELSE STMT_END / 2
							END
						WHEN - 1
							THEN DATALENGTH(TEXT)
						ELSE (
								CASE 
									WHEN STMT_END = - 1
										THEN - 1
									ELSE STMT_END / 2
									END - STMT_START / 2
								)
						END))
		END
	,DB_NAME(A.DBID)
	,A.CMD
	,A.HOSTNAME
	,C.CLIENT_NET_ADDRESS
	,A.LOGINAME
	,A.LOGIN_TIME
	,OBJECT_NAME(G.OBJECTID, G.DBID)
	,A.SPID
	,A.BLOCKED
	,A.PROGRAM_NAME
	,ISNULL(CASE 
			WHEN A.PROGRAM_NAME LIKE 'SSIS%'
				THEN 'JOB-PACKAGE'
			ELSE F.NAME
			END, 'NÃO JOB')
	,WAIT_RESOURCE
	,B.ESTIMATED_COMPLETION_TIME
	,A.CPU
	,E.GRANTED_MEMORY_KB
	,A.[STATUS]
ORDER BY CPUPERCENT DESC   



--DBCC FREESYSTEMCACHE ('ALL') WITH MARK_IN_USE_FOR_REMOVAL



--p_QuantidadeMedicamentoAdquiridaCicloAberto


--SP_RECOMPILE 'p_QuantidadeMedicamentoAdquiridaCicloAberto'

--dbcc inputbuffer (53)

--sp_who2

--SELECT COUNT(codcliente) FROM autorizador..tabseg a JOIN	replicacao..credenciado b ON b.codseg = a.codseg WHERE	codcliente = 1599 AND codcre = 127113