SELECT * FROM  CONTROLE_REPLICACAO 

SELECT TPL_CODIGO FROM CONTROLE_REPLICACAO WITH (NOLOCK)

SELECT COUNT(*) FROM Trata_pbm_log_execucao WITH (NOLOCK)
WHERE tpl_codigo>126115355 AND retorno='XX'

UPDATE CONTROLE_REPLICACAO	
SET tpl_codigo=126115355

select COUNT(*) from AUTORIZACAO with (NOLOCK)



127642441